# use .env
name: ${PROJECT_NAME}

services:
  pg:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    networks:
      - internal

  valkey:
    image: valkey/valkey:alpine3.21
    ports:
      - 6379:6379
    networks:
      - internal

networks:
  internal:
    driver: bridge
